# Generated by Django 5.2.10 on 2026-01-30 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('parties', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='invoices.invoice', verbose_name='الفاتورة')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='parties.party', verbose_name='الطرف')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'قيد',
                'verbose_name_plural': 'القيود',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
